### PR TITLE
Andresgalante post fix

### PR DESCRIPTION
**Pull request by lfryc**
Changed excerpt so that it appears nicely on the News page.

Removed tags that are already expressed in form of platform/module configuration.

Changed formatting of the blog posts to be more visually appealing and less "text-y".

### CODE REVIEW

**Comment by lfryc** [comment]
@corinnekrych @andresgalante could you please review?

**Comment by lfryc** [comment]
I wonder if we need a `swift` tag anyway, since the post itself isn't much swift-related.

**Comment by corinnekrych** [comment]
+1
i'm fine either way: with or without the swift tag

**Comment by andresgalante** [comment]
:+1: I am ok with any decision: to swift or not to swift

**Pull request merged**
